version: "3"

services:
 db:
  image: mysql:8.0.39
  platform: linux/amd64
  container_name: easytodo_db
  environment: 
   MYSQL_ROOT_PASSWORD: root_password
   MYSQL_DATABASE: app_db
  ports: 
  - "3306:3306"
  healthcheck:
   test: mtsqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD
   interval: 3s
   retries: 10
   
    
